[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_micro_loan = "8Mcy3PYdYBAywjq7oweV1LQBaEQqi58hFZJgg3qA9DqN"

[test]
startup_wait = 20000

# [registry]
# url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
